"""Add flooring to RealEstateRecord

Revision ID: 61906c4153c8
Revises: 80c5d5a1509d
Create Date: 2026-02-21 18:10:14.985962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61906c4153c8'
down_revision: Union[str, Sequence[str], None] = '80c5d5a1509d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('real_estate_records', sa.Column('flooring_m_squared', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('real_estate_records', 'flooring_m_squared')
    # ### end Alembic commands ###
