"""Initial commit

Revision ID: 80c5d5a1509d
Revises: 
Create Date: 2026-02-14 22:51:43.423669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80c5d5a1509d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_domains')),
    sa.UniqueConstraint('url', name=op.f('uq_domains_url'))
    )
    op.create_table('domain_regulations',
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('is_allowed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], name=op.f('fk_domain_regulations_domain_id_domains')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_domain_regulations'))
    )
    op.create_table('sites',
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], name=op.f('fk_sites_domain_id_domains')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sites')),
    sa.UniqueConstraint('url', name=op.f('uq_sites_url'))
    )
    op.create_table('crawls',
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_crawls_site_id_sites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crawls'))
    )
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crawl_id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['crawl_id'], ['crawls.id'], name=op.f('fk_records_crawl_id_crawls')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_records'))
    )
    op.create_table('descriptions',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('current', sa.Boolean(), nullable=False),
    sa.Column('text', sa.String(length=16384), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], name=op.f('fk_descriptions_record_id_records')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_descriptions'))
    )
    op.create_table('real_estate_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=2048), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('location', sa.String(length=2048), nullable=True),
    sa.CheckConstraint('(price IS NULL AND currency IS NULL) OR (price IS NOT NULL AND currency IS NOT NULL)', name=op.f('ck_real_estate_records_check_price_currency_together')),
    sa.CheckConstraint('price >= 0', name=op.f('ck_real_estate_records_check_price_non_negative')),
    sa.ForeignKeyConstraint(['id'], ['records.id'], name=op.f('fk_real_estate_records_id_records')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_real_estate_records'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('real_estate_records')
    op.drop_table('descriptions')
    op.drop_table('records')
    op.drop_table('crawls')
    op.drop_table('sites')
    op.drop_table('domain_regulations')
    op.drop_table('domains')
    # ### end Alembic commands ###
